gpu: 0

# Federated arguments
FL:
  round: 100
  num_clients: 100
  frac: 0.1
  test_batch_size: 128
  is_attack: false
  is_defense: true
  aggregator: FedAvg  # useless in foolsgold

# local train arguments
Trainer:
  name: ImageClassificationTrainer
  args:
    local_epochs: 2
    batch_size: 64
    loss_function: nll_loss
    optimizer:
      name: SGD
      args:
        lr: 0.01
        momentum: 0.5

# Dataset arguments
Dataset:
  name: cifar_dataset
  data_dir:

# Sampling arguments
Sampler:
#  name: UniformSampler
#  name: DirichletSampler
  name: NonUniformSampler
  args:
    useless: 0
#    groupby: false
#    alpha: 0.5

# Model arguments
Model:
  name: CNNCifar
#  name: ResNet18
  args:
    num_classes: 10


# Defense arguments
Defense:
  name: FoolsGold
  args:
    use_memory: False

# Attack arguments
Attack:
  name: SemanticAttack
  attack_round: [1]
  poison_images:
    target_label: 2
    ## cars with vertically striped walls in the background: 7 + 5 = 12
    train: [ 568, 33105, 33615, 33907, 36848, 40713, 41706 ]
    test: [ 330, 3934, 12336, 30560, 30696 ]
    ## cars with racing stripes: 15 + 7 = 22
#    train: [ 2180, 2771, 3233, 4932, 6241, 6813, 6869, 9476, 11395, 11744,
#             14209, 14238, 18716, 19793, 20781 ]
#    test: [ 21529, 31311, 40518, 40633, 42119, 42663, 49392 ]
    ## green cars: 21 + 9 = 30
#    train: [389, 561, 874, 1605, 3378, 3678, 4528, 9744, 19165, 19500, 21422,
#                        22984, 32941, 34287, 34385, 36005, 37365, 37533, 38658, 38735, 39824]
#    test: [40138, 41336, 41861, 47001, 47026, 48003, 48030, 49163, 49588]
  args:
    local_epochs: 5
    batch_size: 64
    loss_function: nll_loss
    optimizer:
      name: SGD
      args:
        lr: 0.01
        momentum: 0.5
    stealth_rate: 0
    scale_weight: 10

# other arguments